# .github/actions/publish-python-package/action.yml
name: 'Build and Publish Python Package'
description: 'Installs dependencies, builds, and publishes a Python package to a Gitea repository'

# Define the inputs the action will accept
inputs:
  gitea_username:
    description: 'Username for the Gitea repository'
    required: true
  gitea_password:
    description: 'Password or token for the Gitea repository'
    required: true
  gitea_org:
    description: 'Organization of the Gitea package repository'
    required: false
    default: 'veloslab'
  gitea_domain:
    description: 'The base domain for your Gitea instance'
    required: false
    default: 'gitea.veloslab.lan'
  run_tests:
    description: 'Set to "true" to run pytest before publishing'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - name: Install Poetry
      shell: bash
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Download Gitea CA Certificate
      shell: bash
      run: |
        openssl s_client -showcerts -connect ${{ inputs.gitea_domain }}:443 < /dev/null 2>/dev/null | sed -n -e '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > ca_chain.pem

    - name: Configure Poetry Repository
      shell: bash
      run: |
        # Set up the repository URL and configure Poetry to trust the downloaded CA certificate
        poetry config repositories.gitea https://${{ inputs.gitea_domain }}/api/packages/${{ inputs.gitea_org }}/pypi/
        poetry config certificates.gitea.cert ca_chain.pem

    - name: Install Project Dependencies
      # Use environment variables for authentication when fetching dependencies
      env:
        POETRY_HTTP_BASIC_GITEA_USERNAME: ${{ inputs.gitea_username }}
        POETRY_HTTP_BASIC_GITEA_PASSWORD: ${{ inputs.gitea_password }}
      shell: bash
      run: poetry install --no-interaction --no-root --with dev

    - name: Conditionally Run Tests
      if: inputs.run_tests == 'true'
      shell: bash
      run: |
        echo "Running tests..."
        poetry run pytest

    - name: Build the package distributions
      shell: bash
      run: poetry build

    - name: Publish package to Gitea
      # Use environment variables for authentication when publishing
      env:
        POETRY_HTTP_BASIC_GITEA_USERNAME: ${{ inputs.gitea_username }}
        POETRY_HTTP_BASIC_GITEA_PASSWORD: ${{ inputs.gitea_password }}
      shell: bash
      run: poetry publish --repository gitea --no-interaction
